name: JayKipp
favicon: null
layout_spectrum: 0.16288936464115977
typography_spectrum: 0.7195816158782691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0c7fe'
    - '#586d66'
    - '#b7aaa1'
    - '#040406'
    - '#281f0e'
  brandStrength: 0.8206533116754144
  lightness: 0.9050741661339998
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
